### ISSUE TITLE
Error: connect ETIMEDOUT 104.154.164.197:443

### ISSUE THREAD

**Issue by JasprW** [paviro/MMM-Facial-Recognition#53]
> [MMM-Facial-Recognition] Facerecognition started...
[MMM-Facial-Recognition] Loading training data...
[MMM-Facial-Recognition] ALGORITHM: LBPH
[MMM-Facial-Recognition] Training data loaded!
[MMM-Facial-Recognition] --------------------
[MMM-Facial-Recognition] PiCam ausgewählt...
Whoops! There was an uncaught exception...
{ Error: connect ETIMEDOUT 104.154.164.197:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.154.164.197',
  port: 443 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

It stuck with this error and It seems this IP is blocked in China. What exactly is this IP for? Is there any way to bypass this error or how can I configure a proxy for this module?

**Comment by paviro** [comment]
Are you sure this is from my module?
